export const columns = [
    { key: "title", label: "Tiêu đề" },
    { key: "platform", label: "Platform" },
    { key: "author", label: "Tác giả" },
    { key: "status", label: "Trạng thái" },
    { key: "createdAt", label: "Ngày tạo" },
    { key: "engagement", label: "Engagement" },
    { key: "actions", label: "Thao tác", align: "right" },
];

export const initialPosts = [
    {
        id: 1,
        platform: "facebook",
        title: "Giới thiệu sản phẩm mới của công ty",
        content: "Chúng tôi vui mừng thông báo về sản phẩm công nghệ mới nhất sẽ thay đổi cách bạn làm việc...",
        image: "/modern-tech-launch.png",
        date: "2024-01-15",
        author: "Nguyễn Văn A",
        status: "published",
        tags: "sản phẩm, công nghệ",
        likes: 245,
        comments: 32,
        shares: 18,
        views: 1250,
    },
    {
        id: 2,
        platform: "youtube",
        title: "Hướng dẫn sử dụng phần mềm quản lý",
        content: "Video chi tiết về cách sử dụng các tính năng chính của phần mềm quản lý doanh nghiệp...",
        image: "/software-tutorial-thumbnail.png",
        date: "2024-01-12",
        author: "Trần Thị B",
        status: "published",
        tags: "hướng dẫn, phần mềm",
        likes: 189,
        comments: 45,
        shares: 23,
        views: 3420,
    },
    {
        id: 3,
        platform: "instagram",
        title: "Behind the scenes - Văn phòng làm việc",
        content: "Khám phá không gian làm việc hiện đại và sáng tạo của đội ngũ chúng tôi...",
        image: "/modern-office-behind-scenes.png",
        date: "2024-01-10",
        author: "Lê Văn C",
        status: "draft",
        tags: "văn phòng, team",
        likes: 156,
        comments: 28,
        shares: 12,
        views: 890,
    },
    {
        id: 4,
        platform: "facebook",
        title: "Chia sẻ câu chuyện khách hàng thành công",
        content: "Khách hàng của chúng tôi đã tăng 200% doanh thu sau khi áp dụng giải pháp mới...",
        image: "/customer-success-story.png",
        date: "2024-01-08",
        author: "Nguyễn Thị D",
        status: "published",
        tags: "khách hàng, thành công",
        likes: 320,
        comments: 40,
        shares: 25,
        views: 2100,
    },
    {
        id: 5,
        platform: "linkedin",
        title: "Bài viết chuyên sâu về xu hướng công nghệ 2024",
        content: "Phân tích chi tiết các xu hướng công nghệ sẽ định hình thị trường trong năm tới...",
        image: "/tech-trends-2024.png",
        date: "2024-01-05",
        author: "Phạm Văn E",
        status: "published",
        tags: "công nghệ, xu hướng",
        likes: 410,
        comments: 55,
        shares: 38,
        views: 3500,
    },
    {
        id: 6,
        platform: "twitter",
        title: "Tips nhanh: Tối ưu hiệu suất làm việc",
        content: "3 mẹo đơn giản giúp bạn làm việc hiệu quả hơn mỗi ngày...",
        image: "/productivity-tips.png",
        date: "2024-01-03",
        author: "Lê Thị F",
        status: "published",
        tags: "mẹo, hiệu suất",
        likes: 210,
        comments: 18,
        shares: 45,
        views: 1750,
    },
    {
        id: 7,
        platform: "youtube",
        title: "Phỏng vấn CEO về chiến lược phát triển",
        content: "CEO chia sẻ tầm nhìn và kế hoạch mở rộng thị trường quốc tế...",
        image: "/ceo-interview-thumbnail.png",
        date: "2024-01-02",
        author: "Nguyễn Văn G",
        status: "published",
        tags: "CEO, chiến lược",
        likes: 560,
        comments: 72,
        shares: 60,
        views: 4800,
    },
    {
        id: 8,
        platform: "instagram",
        title: "Ảnh đẹp từ sự kiện ra mắt sản phẩm",
        content: "Những khoảnh khắc ấn tượng từ buổi lễ ra mắt sản phẩm mới...",
        image: "/product-launch-event.png",
        date: "2023-12-30",
        author: "Trần Thị H",
        status: "published",
        tags: "sự kiện, sản phẩm",
        likes: 890,
        comments: 102,
        shares: 75,
        views: 6200,
    },
    {
        id: 9,
        platform: "facebook",
        title: "Thông báo tuyển dụng nhân sự",
        content: "Chúng tôi đang tìm kiếm những ứng viên tài năng cho nhiều vị trí...",
        image: "/job-announcement.png",
        date: "2023-12-28",
        author: "Phạm Văn I",
        status: "published",
        tags: "tuyển dụng, nhân sự",
        likes: 145,
        comments: 20,
        shares: 15,
        views: 980,
    },
    {
        id: 10,
        platform: "linkedin",
        title: "Báo cáo kết quả kinh doanh quý IV",
        content: "Doanh thu tăng trưởng ấn tượng, vượt 15% so với kế hoạch...",
        image: "/q4-report.png",
        date: "2023-12-25",
        author: "Nguyễn Thị J",
        status: "published",
        tags: "báo cáo, kinh doanh",
        likes: 275,
        comments: 34,
        shares: 22,
        views: 2100,
    },
    {
        id: 11,
        platform: "youtube",
        title: "Livestream hỏi đáp với khách hàng",
        content: "Giải đáp các thắc mắc và chia sẻ thông tin mới nhất về sản phẩm...",
        image: "/livestream-qa-thumbnail.png",
        date: "2023-12-22",
        author: "Lê Văn K",
        status: "published",
        tags: "livestream, khách hàng",
        likes: 340,
        comments: 65,
        shares: 40,
        views: 3900,
    },
    {
        id: 12,
        platform: "instagram",
        title: "Hình ảnh team building cuối năm",
        content: "Khoảnh khắc vui vẻ và gắn kết của toàn bộ công ty...",
        image: "/year-end-teambuilding.png",
        date: "2023-12-20",
        author: "Trần Thị L",
        status: "published",
        tags: "team building, sự kiện",
        likes: 760,
        comments: 88,
        shares: 54,
        views: 5400,
    },
    {
        id: 13,
        platform: "facebook",
        title: "Chia sẻ kiến thức: Marketing Online",
        content: "Những nguyên tắc vàng giúp chiến dịch marketing online thành công...",
        image: "/online-marketing-tips.png",
        date: "2023-12-18",
        author: "Nguyễn Văn M",
        status: "published",
        tags: "marketing, kiến thức",
        likes: 420,
        comments: 50,
        shares: 33,
        views: 3100,
    },
    {
        id: 14,
        platform: "linkedin",
        title: "Hợp tác chiến lược với đối tác quốc tế",
        content: "Ký kết hợp tác mở rộng thị trường sang châu Âu...",
        image: "/strategic-partnership.png",
        date: "2023-12-15",
        author: "Phạm Thị N",
        status: "published",
        tags: "hợp tác, đối tác",
        likes: 380,
        comments: 44,
        shares: 29,
        views: 2900,
    },
    {
        id: 15,
        platform: "twitter",
        title: "Cập nhật phiên bản phần mềm mới",
        content: "Phiên bản mới cải thiện hiệu suất và bổ sung nhiều tính năng hữu ích...",
        image: "/software-update.png",
        date: "2023-12-12",
        author: "Lê Văn O",
        status: "published",
        tags: "phần mềm, cập nhật",
        likes: 260,
        comments: 30,
        shares: 20,
        views: 2000,
    },
    {
        id: 16,
        platform: "youtube",
        title: "Case study: Dự án thành công",
        content: "Phân tích chi tiết một dự án tiêu biểu và các yếu tố dẫn đến thành công...",
        image: "/case-study-thumbnail.png",
        date: "2023-12-10",
        author: "Nguyễn Thị P",
        status: "published",
        tags: "case study, dự án",
        likes: 500,
        comments: 60,
        shares: 42,
        views: 4500,
    },
];
export const platformColors = {
    facebook: "bg-blue-600 admin-dark:bg-blue-500",
    youtube: "bg-red-600 admin-dark:bg-red-500",
    instagram: "bg-gradient-to-r from-purple-600 to-pink-600 admin-dark:from-purple-500 admin-dark:to-pink-500",
};

export const platformNames = {
    facebook: "Facebook",
    youtube: "YouTube",
    instagram: "Instagram",
};

export const statusColors = {
    published: "bg-green-600 admin-dark:bg-green-500",
    draft: "bg-yellow-600 admin-dark:bg-yellow-500",
    archived: "bg-gray-600 admin-dark:bg-gray-500",
};

export const statusNames = {
    published: "Đã xuất bản",
    draft: "Bản nháp",
    archived: "Lưu trữ",
};